 
---
  - name: Provision an EC2 Instance. 
    hosts: local
    connection: local
    gather_facts: False
    tags: provisioning
    
    vars:
      instance_type: t2.micro
      security_group: docker_sg1
      image: ami-03a0c45ebc70f98ea
      keypair: winkp
      region: us-east-2 
      count: 1
 
 
    tasks:
 
      - name: Create a security group
        local_action: 
          module: ec2_group
          name: "{{ security_group }}"
          description: Security Group for  EC2 Servers
          region: "{{ region }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
            - proto: all
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0  
        register: basic_firewall
        
      - name: Launching new EC2 Instance
        local_action: ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true
                      wait_timeout=500 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{count}}
        register: Docker_VM
 
      - name: Add the newly created EC2 instance ip into textfile
        local_action: lineinfile 
                      path=Docker_VM.txt
                      regexp={{ item.public_ip }} 
                      insertafter='\[Docker_VM\]' line={{ item.public_ip }}
        with_items: '{{Docker_VM.instances}}'
 
      - name: Add new instance to  host group
        add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
        with_items: "{{ Docker_VM.instances }}"
 
      - name: wait for SSH to come up
        local_action: wait_for 
                      host={{ item.public_ip }} 
                      port=22 
                      state=started
        with_items: '{{ Docker_VM.instances }}'
 
      - name: Add tag to Instance
        local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
        with_items: '{{ Docker_VM.instances }}'
        args:
          tags:
            Name: Ansible_VM	 
